# Generated by Django 5.0 on 2024-01-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteModel',
        ),
    ]
