# Generated by Django 5.0 on 2024-01-06 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_delete_notemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotesCategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.notecategorymodel')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.notemodel')),
            ],
            options={
                'unique_together': {('note', 'category')},
            },
        ),
        migrations.AddField(
            model_name='notemodel',
            name='category',
            field=models.ManyToManyField(through='note.NotesCategoriesModel', to='note.notecategorymodel'),
        ),
        migrations.AddIndex(
            model_name='notemodel',
            index=models.Index(fields=['user_id'], name='note_notemo_user_id_388db6_idx'),
        ),
    ]
